FROM ubuntu/apache2:2.4-22.04_beta

COPY utils/apache/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod actions alias proxy_fcgi rewrite headers

RUN service apache2 restart
