services:
  php:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    links:
      - db
    volumes:
      - ./src:/var/www/html/
    profiles:
      - dev
      - prod
  web:
    build:
      dockerfile: Dockerfile-apache
    image: ubuntu/apache2:2.4-22.04_beta
    restart: unless-stopped
    tty: true
    links:
      - php
    ports:
      - "127.0.0.1:${WEB_PORT:?}:80"
    volumes:
      - ./src/:/var/www/html
      - ./data/apache2/logs:/var/log/apache2
    profiles:
      - dev
      - prod
  db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    expose:
      - "127.0.0.1:${MYSQL_PORT:?}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:?}"
      MYSQL_USER: "${MYSQL_USER:?}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?}"
    profiles:
      - dev
      - prod
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 50M
    restart: "no"
    ports:
      - "28001:80"
    profiles:
      - dev