services:
  php:
    build:
      dockerfile: Dockerfile
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - "8000:8000"
    restart: unless-stopped
    tty: true
    volumes:
      - /app/vendor
      - ./src:/app
